### ISSUE TITLE
Search component incorrectly performs initial search immediately

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#10]
while working on the sdk-components-example-angular-app repo I noticed a *ExpressionChangedAfterItHasBeenCheckedError* in the console. The bug is that the SzSearchComponent is immediately performing a search when no values have changed. I believe this is related to the following console statement:
```
@senzing/sdk/search/sz-search/sz-search.component.submitSearch:  {IDENTIFIER_TYPE: "PASSPORT_NUMBER", NAME_TYPE: "PRIMARY"}
```

It appears to be incorrectly filtering the search params and immediately executing a query.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/sdk-components-ng/pull/12
