### ISSUE TITLE
Integrate new sdk-graph-components features

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#105]
![2019-10-18_203116](https://user-images.githubusercontent.com/13721038/67137209-5c034100-f1e6-11e9-9983-9f0cc233246e.png)

- will add prefs entries for datasource colors, which will use new "highlight" graph method
- will add array pref modifier component and add it to the prefs ui component for datasource colors
- will create new *graph filter* ui component which will use new "filter" graph method. graph filter 
components should:
   - allow user to hide data from specific datasources
   - provide slider for maxEntitties pref
   - provide slider for buildOut pref
   - provide color swatch picker for any datasource listed

- will add passthrough methods for *filter*, *merge*, and *highlight*  access to the inner graph network component.
graph filter component, as well as graph control should be exported to package index and module

will also add new @Output event for clicking on new "pop-out" icon in lower corner of embedded network graph, and any modifiers necessary to make that work.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/sdk-components-ng/pull/106
