### ISSUE TITLE
Add "History" feature to search component

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#109]
It's been proposed that we provide a mechanism to pre-populate searches, and/or allow users to save search parameters in some way.

The sdk-components should provide a data model/datastore to allow the search form to provide pulldown/type-ahead history of searches that have been recently performed in the last X times etc. The component itself should not store any data, just provide the input mechanism for the implementing application to get/set the history using the datamodel. That way by default no data would be stored, but then on event, the implementation could get the data and store it using their own storage options. Then to populate the history, it should allow the implementation to set  the history list. 

It is a very similar design pattern to how preferences are implemented.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/entity-search-web-app/issues/119
