### ISSUE TITLE
Create an additional search interface that permits the user to search by the entity or record ID.

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#110]
**What:**
Create an additional search interface that permits the user to search by the entity or record ID.

**Why:**
In addition to being very useful in demos and show-n-tell valid customer workflows to want to pull up an entity via entity ID or record ID

Very useful to have available where applications are looking to us to embed such as the i2 work

**Context:**
Today we expose search
There are 2 other common mechanisms and API calls to recall entity details
 
- getEntityByRecordIDV2
- getEntityByEntityIDV2
- http://docs.senzing.com/1.11/index.html#data-query-and-search

- Like search these return the resume for the entity for reporting and visualization purposes
- Add these ‘get’ capabilities in addition to search
- Suggest a distinct component in addition to the search one

getEntityByEntityIDV2
Used when user or application has already located the entity ID and now wants additional data if they didn’t have full resume yet

- getEntityByEntityIDV2 arguments
 - entityID
 - flags
  - - Control flags to determine level of information returned 
  - - Level should be correct to return the resume to display as search does and to graph

**Suggested Approach** (Ant)
From the default search page, in the tripple dot menu, offer a menu item:

“Search by ID”
![image](https://user-images.githubusercontent.com/13721038/68691920-6d134980-0529-11ea-84b7-b128f58787a5.png)

**Comment by arawinters** [comment]
see PR #113 for implementation specifics.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/entity-search-web-app/issues/113
