### ISSUE TITLE
Make datasource colors adhere to order of operations

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#111]
right now the order of which colors to apply to elements in the graph is not relevant, it's last datasource matched is what color gets applied. So if a entity belongs to 3 different datasources, its always the last color specified that gets applied to the element. The user should be able to specify the order of color filters as they get applied to the dataset. 

Currently the data model used for applying color filters to entity nodes is:
```
{
   "dataSourceName1": "green",
   "dataSourceName2": "blue",
   "dataSourceName3":"orange"
}
```
it needs to be in the form of an array to preserve order, ie:
```
[
   {"name": "dataSourceName1", "color": "green"},
   {"name": "dataSourceName3", "color": "orange"},
   {"name": "dataSourceName2", "color": "blue"},
]
```

The other thing that needs to happen is to provide a mechanism for choosing the order. drag-to-reorder would be the optimal solution but might be rather technical to implement without including third-party ui toolkits in the sdk.. which.. we should avoid if we can(toolkits inside of toolkits 👎 ). I suggest just prototyping it using up/down arrows first, then work on upgrading that to drag to re-order.

![2019-11-12_092810](https://user-images.githubusercontent.com/13721038/68694844-c5991580-052e-11ea-9a9f-de5f554fb286.png)

**Comment by missulmer** [comment]
Keep open will solve.
