### ISSUE TITLE
Add info/version/diagnostics service to package

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#114]
While working on https://github.com/Senzing/entity-search-web-app/issues/68 I found several functionality gaps:
1. was that some data model info was missing when compared with api-server responses. 
2. was that it would be much cleaner if the sdk components provided a service to expose version/diagnostic information instead of having to Frankenstein one from the rest-api-client-ng package

we should fix that by exporting a service in the package to act as tidy wrapper for requesting this information..  the service should wrap the requesting of:
- `/version`
- `/license`
- `/heartbeat` 

(see [OAS spec](http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api/master/senzing-rest-api.yaml#operations-tag-Admin))

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/entity-search-web-app/issues/120
