### ISSUE TITLE
Split "search-with-prefs" example off from "by-record-id"

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#115]
I co-opted the "search-with-prefs" example project for testing out the new "by record id/entity id" component( #113 )

The code should be copied to a separate example project and the existing example code should be reverted to it's previous state.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/entity-search-web-app/issues/113
1. https://github.com/Senzing/entity-search-web-app/issues/118
1. https://github.com/Senzing/entity-search-web-app/issues/120
