### ISSUE TITLE
Fix hardcoded graph filter width

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#121]
The graph filter width is just set to a hard calc expression: 
```scss
width: calc( 100% - 340px)
```
there are cases where the width should just be `width: 100%`, like when the `showFilters == false` there is no need to subtract the 340.

We also need a event to support external usage of the graph filter component. 
specifically we need an event for proxying the internal `onGraphDataLoaded` of `#graph` element in sz-standalone-graph.component.ts to a local `onDataLoaded` event emitter that can be listened for.  (related ticket: https://github.com/Senzing/entity-search-web-app/issues/74)

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/entity-search-web-app/issues/122
