### ISSUE TITLE
Fix Search History feature

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#123]
fixes for #119 
(see https://github.com/Senzing/entity-search-web-app/issues/84)

There is a bug in the new "Search History" feature where if there are no previous searches in history then the prefs never initializes a new empty search history folio. Which has chicken-and-egg effect where because there **_WAS_** no history, there **_WILL BE_** no history.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/entity-search-web-app/issues/124
