### ISSUE TITLE
Update to Angular 11

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#206]
We should update the library to compile using [angular-cli@11.0.0](https://github.com/angular/angular-cli/releases/tag/v11.0.0) This will update the library to compile using the newest versions of dependencies, tooling, and schema's. 

The end user should see no difference since it just affects those trying to compile from source. The end result _**should**_ still be a package that is compatible with projects based on older releases of angular.

### Note: this update is being performed in multiple repositories simultaneously.

**Comment by jamietypovsky** [comment]
Closing this due to the release of Angular 12.
