### ISSUE TITLE
Fix doc thumbnails

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#4]
the thumbnail images for https://senzing.github.io/sdk-components-ng/additional-documentation/themes/pre-built.html are off by a directory.

ie: 
https://senzing.github.io/sdk-components-ng/additional-documentation/images/themes/add-to-style-paths.png
should be:
https://senzing.github.io/sdk-components-ng/images/themes/add-to-style-paths.png

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/sdk-components-ng/pull/14
