### ISSUE TITLE
Update Themes/Themes Docs

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#5]
Some things have changed between pre-alpha and alpha. The default themes that are bundled with the package are out of date. 

The result is that when using the package as a dependency in a project, the themes look a bit ugly.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/sdk-components-ng/pull/12
1. https://github.com/Senzing/sdk-components-ng/pull/14
