### ISSUE TITLE
Add error bubbling/eventing

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#6]
right now if something goes wrong with an api request from inside the rest-api-client-ng lib the components do not bubble the events up through any observeable output streams.

I propose adding:
```typescript
@Output() onError: EventEmitter<Error> = new EventEmitter<Error>();
```
to all the components. and we can catch the errors in the components, then surface the errors via:
```typescript
this.onError.next( new Error("something went wrong.") )
```

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/sdk-components-ng/pull/12
1. https://github.com/Senzing/sdk-components-ng/pull/14
