### ISSUE TITLE
Update css for responsive breakpoint(s) and/or reflow on narrow width

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#94]
there is an ask to reflow the entity detail and search form component when the display area is below a certain width. The top summary columns need to wrap or change from row to column layout when < min area.  Same thing with search results but the opposite, cols should display left to right, currently they stack vertically.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/sdk-components-ng/pull/95
